### ISSUE TITLE
Narrow width breaks prompts

### ISSUE THREAD

**Issue by ac360** [serverless/components#422]
Whoops, we're running into the narrow width issue again w/ CLI prompts.  In a narrow CLI, toggling through options repeats the prompt, like this:

<img width="663" alt="Screen Shot 2019-04-05 at 3 52 59 PM" src="https://user-images.githubusercontent.com/2752551/55660411-0a9be300-57bb-11e9-848a-ed259c173eee.png">

**Comment by eahefnawy** [comment]
I've debugged this, and I was easily able to reproduce it even outside of our repo. I think it's a bug in the [prompts](https://github.com/terkelg/prompts) package

[I've opened an issue over there](https://github.com/terkelg/prompts/issues/153), meanwhile, I think we better switch to a different prompt, since this issue happens with the default terminal width.

**Comment by eahefnawy** [comment]
Fixed & published by switching to inquirer.
