### ISSUE TITLE
add support for ${env.SOME_ENV_VAR}

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#477]
Add support for resolving environment variables via serverless.yml. Requested by @Pavel910

**Comment by Pavel910** [comment]
And while you're at it, could we also have access to, for example, `${opt:stage}`?
I need to pass the stage to `inputs.hook` so, for example, a build script knows what webpack config to use, etc.

**Comment by eahefnawy** [comment]
hmmm thanks for suggesting @Pavel910 ... we're trying real hard to not over complicate our variable system like we have in the framework. I think the env one makes sense, but I'm on the fence with the `opt` one. 

We don't wanna tie the template to the CLI. Remember that components could also be used programmatically, not just via the CLI. If you programmatically pass a template with that reference, how would this variable get resolved? 🤔 

Would love to get further feedback. 😊 Overall, if your yaml file does not satisfy your needs, you could have complete programatic power with a simple `serverless.js` file.

**Comment by Pavel910** [comment]
@eahefnawy actually it doesn't even have to be the entire `opts`, the only thing I really am missing is the ability to identify what stage is being deployed.

My specific goal at this point is to create a custom component that will deploy a React app with full support for server-side-rendering (so it is basically deployed as a plain lambda function) + I need to be able to pass the `stage` data to the webpack build process, because JS app routing depends on the `/dev`/`/prod` prefixes of the API Gateway, and it has to be known at build time.

Let me know if it is possible, if not - I will just have to figure out a different approach to solve the problem. Thanks :)

**Comment by eahefnawy** [comment]
The way we handle stages right now is by keeping each stage in a different account with`.env.STAGE` creds file. I do get your use case for trying to access the stage in the yaml file 🤔 ... maybe something like this `${ctx.stage}`? in that case `ctx` would work both programmatically and declaratively, so I'd prefer that over opts. I think in general it might be a good idea to reference the context in a YAML file.

**Comment by Pavel910** [comment]
That is a great idea! Nothing more to add here, that's it 👍 

It solves not only my problem with a custom component, but also allows you to customize hook scripts with your existing components, like `website`, etc.

**Comment by laardee** [comment]
I'll start working on this feature.

**Comment by eahefnawy** [comment]
This is now supported thanks to @laardee 🙌 

https://github.com/serverless/components#environment-variables
