### ISSUE TITLE
Why is Components not based on CloudFormation?

### ISSUE THREAD

**Issue by mnapoli** [serverless/components#479]
# Description

This issue isn't really a bug or problem. I am curious about the decision why CloudFormation isn't used, like in Serverless itself. I have searched for a documented reason in existing issues but didn't find it.

I am opening this issue so that the reason is documented somewhere.

Since I have had a few people dismiss Serverless Components because of that, it would also be useful to me to be to explain clearly the reasons behind that choice, and what are the pros and cons.

If you consider this isn't a valid issue feel free to close this.

**Comment by eahefnawy** [comment]
Thanks for opening this up @mnapoli ... This is a common question, so I'll just post in @ac360 excellent answer on the matter from our Slack channel.

> After spending 4+ years building tools on top of CloudFormation, we no longer agree it’s the best way to provision infrastructure, especially in the serverless era.
Our users care more about use-cases and outcomes, not complex, low-level infra configuration.  They care about fast deployments, custom deployments, and more useful automation than just deploy/remove.
Without CloudFormation we can:
• Offer 100x faster deployments.
• Be totally free to offer any type of simpler configuration.
• Do special deployments for specific use-cases (e.g. better blue+green deployments).
• Offer a better, singular vendor agnostic experience enabling you to deploy Stripe/Google/AWS.
• Ship Components w/ more automation than deploy/remove, like test/seed/register domain/and much more.
• And much more.
We’re here to innovate better serverless tooling, but CloudFormation has limited us for years.  You’ll still have many CloudFormation options.  But, we’re looking to offer faster, smarter, simpler tooling/automation, and moving beyond CloudFormation is key to this.

Hope this helps! Would love to hear everyone's thoughts on the matter 😊

**Comment by eahefnawy** [comment]
Adding to that the rest of the discussion, which highlights the fact that you can in fact use CloudFromation via the [aws-cloudformation component](https://github.com/serverless-components/aws-cloudformation)

> You can still use the normal Serverless Framework experience.
•  We’ve also designed a slick AWS CloudFormation Component, which can deploy any CloudFormation template, and it automatically makes the CF Outputs Serverless Component outputs, so that you can pass those outputs easily into any other Component - https://github.com/serverless-components/aws-cloudformation
•  Components for SAM, Terraform, Chef, and more are coming.
Our users will now have more options than ever and better integrations into tools other parts of their company are using.
That said, our main goal of Components to offer better automation for specific use-cases where serverless infra is strong.  General infra provisioning systems do the least possible amount of automation when it comes to managing your use-case and its lifecycle.  We are going to do a lot more…  Example:  The Serverless REST API Component should know how to test itself.  It should know how to do blue/green deployments.  It should know how to set up a custom domain or SSL cert for you.
We can do so much more than deploy and remove, and we’re going to do it so you don’t have to.

**Comment by mnapoli** [comment]
Oh right that definitely helps! I was skeptical but now I'm excited! That makes a lot of sense!

Should I close this issue now?

Now I'm off to watching #450 👀

**Comment by eahefnawy** [comment]
Yep, let's close it 😊

**Comment by morgler** [comment]
Your tiny information about how to export outputs from the "old" serverless world (i.e. CloudFormation without components) to the "new" world (i.e. components) was something I had been searching for for hours! Maybe it would be a good idea to mention the AWS CloudFormation Component and that it allows to communicate outputs to serverless components in the components documentation.
