### ISSUE TITLE
Component: AWS AppSync

### ISSUE THREAD

**Issue by ac360** [serverless/components#480]
...

**Comment by eahefnawy** [comment]
So I did some digging here, and I think it should be fairly straightforward to implement it as a component. However, we won't be doing much abstraction for the user. So the UX will be slightly better than using the console/CF, but because this is a low level component, it's still gonna be fairly verbose (you'll need to specify a graph schema, as well as request/response template files)

if we wanna abstract more, we may create a `@serverless/graphql` component in the future that uses that and abstracts away at least the AWS request templates.

**Comment by eahefnawy** [comment]
Ok thinking about it a bit further, I think it'll be a lot easier and a lot better experience to build the graphql component first. There are a lot of resources involved in AppSync that can be abstracted away.

I think we can provide an optimal UX that is similar to the `backend` component by having it look like this.

```yml
api:
  component: "@serverless/graphql"
  inputs:
    schema: ./schema.graphql
    resolvers: ./resolvers.js
```

I think I can set it up in a way that only requires these two input files. Everything else AppSync requires is redundant for this use case imo. If you wanna set other sources (ie. DynamoDB or HTTP), you can use the lower level `@serverless/aws-app-sync` component.

**Comment by LaszloDev** [comment]
What is the status of the [AWS AppSync component](https://github.com/serverless-components/aws-app-sync/)? 

The project itself does look abandoned, checkout the latest issue
https://github.com/serverless-components/aws-app-sync/issues/32

**Comment by eahefnawy** [comment]
Thanks @LaszloDev ... replied:
https://github.com/serverless-components/aws-app-sync/issues/32#issuecomment-633476213
