### ISSUE TITLE
Stage Support

### ISSUE THREAD

**Issue by hoang-innomizetech** [serverless/components#481]
What are the best practices to create multiple environments using serverless components? For example, I wanted to configure a website for my prod, staging, dev environments. Not sure whether we can use stage option likes `serverless deploy --stage prod` command

**Comment by eahefnawy** [comment]
@hoang-innomizetech components are all about instances rather than stages. And because we don't have support for remote state storage yet, all components state is saved in the `.serverless` dir in the cwd. So to support your use case, you could deploy two instances of the same component using two directories.

```
code:       # this directory includes all your code
  |- index.js # this is where you export all your functions
  |- package.json

dev:
  |- serverless.yml # this is the dev stage. Just run `sls` here

prod:
  |- serverless.yml # this is the prod stage. Just run `sls` here
```

just don't forget to point to the code dir if you're using a component that requires code input:


```
backend:
  component: "@serverless/backend"
  inputs:
    code: ../code # this is IMPORTANT
```

**Comment by Pavel910** [comment]
@eahefnawy so now you always deploy everything to API Gateway `/dev` path? That's what my tests are showing, wanted to get a confirmation that this is the intended behavior. Thanks!

**Comment by eahefnawy** [comment]
@Pavel910 for the `aws-api-gateway` component, you could pass a stage as an input. Here's an example:
https://github.com/serverless-components/backend/blob/master/serverless.js#L107

In that case though, the stage as a concept is applied to the APIG component only, but not a "global stage concept"

**Comment by juank11memphis** [comment]
@eahefnawy I like a lot your approach for multiple environments. Even though my only concern is that the serverless.yml files for each environment would end being pretty much identical, is there a way to avoid this in the current serverless components implementation?

**Comment by hoang-innomizetech** [comment]
The component allow passing config param, I aws able to custom it but when removing it takes the current state, so it was wrong. I think support env variable would be the best approach for all components.

**Comment by Pavel910** [comment]
I am currently using the approach with a folder-per-environment @eahefnawy suggested, and it works nicely. Maybe a little repetitive - yes, but everything is very explicit and isolated. Besides being well isolated, it also offers you a way to quickly create completely new experimental configs and deploy those before changing your prod/staging configs.

**Comment by juank11memphis** [comment]
I agree with @hoang-innomizetech that the best approach would be for components to accept an env variable, having the same yml file for each environment still does not sounds great to me.

**Comment by Pavel910** [comment]
@juank11memphis the problem is that `sls` needs to somehow correlate the `state` to the `.env` file you used. Each environment must have a separate state (`.serverless` folder). 

@eahefnawy maybe if we could manually provide an instance id to the CLI this could work in conjuction with the [env-cmd](https://www.npmjs.com/package/env-cmd) package. That way we could say `env-cmd -f .env.dev sls --id=dev` or `env-cmd -f .env.prod sls --id=prod` 🤔

**Comment by eahefnawy** [comment]
> @eahefnawy maybe if we could manually provide an instance id to the CLI this could work in conjuction with the env-cmd package. That way we could say env-cmd -f .env.dev sls --id=dev or env-cmd -f .env.prod sls --id=prod 🤔

@Pavel910 you're right on the money! This is **exactly** what we're planning to do eventually! 😅 .. ... We're thinking along the lines of "instanceIds" rather than stages. Just naming the top level component is enough to create a completely new stack!

**Comment by barrysteyn** [comment]
@eahefnawy It seems like adding CLI support for an instance id would be a very quick win. I am unable to convince my team to go forward with components unless I am able to deploy a dev instance. Also, the yml would need variable interpolation. In my tests, when I did this: `name: xyz-${env.STAGE}`, it ignored the *xyz-* and just used the *${env.STAGE}*.

It seems to me that this would be an easy win.

**Comment by hoang-innomizetech** [comment]
Yeah, instance id or state can solve the real-world problem.

**Comment by uxtx** [comment]
@barrysteyn wrt variable interpolation - converting your serverless.yml file to a javascript file seems to be the preferred way to go - in that it unlocks a lot more flexibility in your customizability - for example:

```
'use strict';

const program = require('commander');
const merge = require('deepmerge');

program.option('--stage <n>', 'stage').parse(process.argv);

const validNames =  {
    'dev': 'foo',
    'staging': 'bar'
}

function combine() {
    let stage = program.stage || 'dev';
    // No prod for now.
    const validStages = ['dev', 'staging'];
    // if our stage doesn't match our valid stage - default to dev.
    if (validStages.indexOf(stage) < 0) {
        stage = 'dev'
    }
    const myName = validNames[stage];
    const componentConfig =  {
        name: myName,
        webapp: {
            component: '@serverless/website',
            inputs: {
                code: {
                    src: 'dist',
                    root: 'webapp',
                    hook: 'npm run build'
                },
                env: {}
            }
        }
    }
    return merge({}, componentConfig);
};
module.exports = combine()
```

**Comment by Pavel910** [comment]
@eahefnawy could you please tell me what are the downsides of this approach:
so the idea is to create a `serverless.js` right next to your `serverless.yaml`, which could then accept `--env` parameter, and set that as an `alias` to the `@serverless/template` and thus create a environment-based prefix for state files:

```js
const path = require("path");
const { Component } = require("@serverless/core");

class Deploy extends Component {
    async default(inputs = {}) {
        const template = await this.load("@serverless/template", inputs.env);

        const output = await template({ template: path.join("serverless.yaml") });

        return output;
    }
}

module.exports = Deploy;
```

Running `sls --env=dev` would create state files `Deploy.dev.json` or `Deploy.prod.json` etc. depending on the `env` you pass as the input. This would easily allow to load whatever `.env` file you want, depending on you `env` input.

Since the `template` is constructed using the alias, all child components point to the correct state file and it all seems to work fine.

Could you confirm if this can work, or point me to what's wrong with this idea? Thanks.

**Comment by barrysteyn** [comment]
@uxtx I want a yml file because it is declarative. I don't mind using js if I am going to be making my own component. It would have worked out if I could have loaded a yml file from a js file, however that seems impossible.

**Comment by Pavel910** [comment]
@barrysteyn see me comment above, it shows how to load a YML file from within your own JS file.
Btw. the `template` input can be an object, not only a path to the file.

**Comment by barrysteyn** [comment]
@Pavel910 Yes, I saw your example. And it looks awesome and clever. But (if you don't mind me saying this), it looks a little hacky. BTW: I can't find any info on @serverless/template

**Comment by Pavel910** [comment]
@barrysteyn actually it is not hacky at all, it is an official way of doing it. Let me give you some references so you can see for yourself :) It took me some digging to discover all this since not everything is documented yet, that's the reason you couldn't find much info on that particular component.

So the first and obvious one is the [@serverless/template](https://github.com/serverless/template/blob/master/serverless.js) component itself, which takes `template` input and parses YAML, builds dependency tree and executes components. It also downloads npm packages to your `~/.serverless/components/registry/npm` folder.

And the second part of mystery is the CLI, which does exactly what I did in the example above:
https://github.com/serverless/cli/blob/master/src/index.js#L178.

The way CLI works is, it simply detects the type of your config/template file and if it a YAML it passes it to the `@serverless/template` component, otherwise it runs the component from the `serverless.js`.

<hr>
Using this approach we managed to build a component which provides a much better DX for our project, with support for environments, better messages, help output, all based on this approach. Here are some screenshots from our own product, based on `serverless`: 

![image](https://user-images.githubusercontent.com/3920893/67156639-91607980-f321-11e9-8413-17839ee9ccaa.png)

And a help output:
![image](https://user-images.githubusercontent.com/3920893/67156647-ac32ee00-f321-11e9-94d4-b6085d77c413.png)

Let me know if you have questions, I may be able to answer them since I'm deep into components since day 1 they were announced :) 🍻

**Comment by barrysteyn** [comment]
@Pavel910 This is extremely cool :)

**Comment by hoang-innomizetech** [comment]
Follow @barrysteyn approach, now we can deploy/remove a website that supports stage/env
https://github.com/hoang-innomizetech/sls-website-example/blob/master/serverless.js

**Comment by eahefnawy** [comment]
@Pavel910 this is EXACTLY why we are going programatic first! And this is also why the yaml experience is just a component under the hood. Instead of supporting a huge variable system and complicated yet powerful YAML file like we've done with V1, we are now keeping YAML simple and allowing users to use JS files, since you could do anything you want with JS without learning something new.

And as @Pavel910 mentioned, this is not at all hacky, we've always believed that if you want to have more power and flexibility, you should use a JS file, in which case you could do anything!.

Thanks for sharing that @Pavel910 😊

**Comment by barrysteyn** [comment]
Version 1.1.12 @serverless/template breaks the example above. It seems to get this working, it would take some time reading source code and understanding things. Could I please request @Pavel910 to update his example above to use the new template.

**Comment by Pavel910** [comment]
@barrysteyn Post the exact code you tried to run and your YAML, and lastly, how you ran the `sls` command (parameters, etc.). Without concrete examples all we can do here is guess.

**Comment by barrysteyn** [comment]
Sorry @Pavel910, here is my serverless.yml
```
name: tenantree-prod

nextApp:
  component: serverless-next.js
  inputs:
    nextConfigDir: "../../"

reviewsTable:
  component: "aws-global-dynamodb"
  inputs:
    tableName: ${env.reviewsTable}
    replicationGroup:
      - "us-west-2"
    attributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: propertyId
        AttributeType: S
    keySchema:
      - AttributeName: propertyId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
```
Here is the serverless.js code:

```
const path = require("path");
const { Component } = require("@serverless/core");

const appName = "tenantree";

const getEnv = ({ env, ...inputs }) => ({
  reviewsTable: `${appName}-${env}-reviews`,
  propertiesTable: `${appName}-${env}-properties`,
  ...inputs,
});

/**
 * Will deploy the serverless component 
 */
class Deploy extends Component {
    async default(inputs = {}) {
      console.log("------>", inputs.env);
      if (inputs.env === 'staging' || inputs.env === 'prod') {
        const template = await this.load("@serverless/template", inputs.env);
        // const output = await template({ template: path.join("serverless.yml") });
        // return output;
      } else {
        this.context.log('No environment defined... Choices are staging and prod');
      }
    }
}

module.exports = Deploy;
```

The serverless.js was based on the code you provided above. However this won't work anymore. I know based on the PR for the severless component that it will run a custom method in the yml (awesome). However it fails when trying to load the component.

**Comment by Pavel910** [comment]
@barrysteyn it's not a bug. Your `serverless.js` is missing the key thing - the custom method itself :) In your code you only have `default` method, which only serves for `deploying`.

Say your custom method is `install`, you need to add that method to `serverless.js`:

```js
class Deploy extends Component {
    /* ... skipped default method for brevity ... */
    
    async install(inputs = {}) {
        // inputs will contain whatever you pass as CLI arguments - not the template inputs.
        const template = await this.load("@serverless/template", inputs.env);
        await template.install(inputs);
    }
}
```

Now run it like `sls install --component reviewsTable` - and this will execute the `install` method on your `aws-global-dynamodb` component.

**Comment by barrysteyn** [comment]
@Pavel910 Many many thanks.

**Comment by Pavel910** [comment]
@barrysteyn The key is to pass an `alias` (the second parameter to `this.load()` method), which then creates a state file name with that prefix. As you may have noticed, the `.serverless` folder contains state files. The name of those files is constructed using the `alias` you pass to `this.load()` or the component class name if no alias is present: https://github.com/serverless/components/blob/master/src/Component.js#L111

So you still have the same `id` in your `_.json`, but the state files can be grouped by `env` for example. If you load your template file with `this.load("@serverless/template", inputs.env)`, the state files will contain that `inputs.env` value in their name and the appropriate state files will be loaded.

That's how I deploy unlimited number of `environments` or `stages`, whatever you call them, in my project. Works like a charm :)

**Comment by barrysteyn** [comment]
@Pavel910 I think here is the disconnect:

 1. You need to pass an id into @serverless/template in order to create an `environment` or `stage`
 2. With the latest change to @serverless/template, you can only pass an id when loading the template if you have defined a custom method
 3. However, we want an id that is applicable to the deploy stage (default method), not a custom method. The latest change will not work like this.

So the problem I am having with using the latest @serverless/template is how to pass that id without needing to have a custom method. Unless the new approach is to have a custom method for deploying in the serverless.js that will then call the default deploy methods of the yml file?

**Comment by Pavel910** [comment]
@barrysteyn make sure your `@serverless/core` is at `1.1.2`, as this feature of invoking custom methods doesn't work if you use an older version of `core` package. See this PR where it clearly states why it is necessary: https://github.com/serverless/components/pull/509.

And if you still have a problem, you need to open a github repo with your reproduction case I can dive in and see. Without a reproduction case I can't really help. All of this is working perfectly in my projects so you'll have to give as a repro case.

**Comment by Pavel910** [comment]
@barrysteyn and there IS a bug when using `template` programmatically, I'll take a look at it.

**Comment by mstn** [comment]
@Pavel910 @barrysteyn  thanks for sharing! Very helpful information, indeed. Out of curiosity, do you share `.serverless` folder on git? With this approach individual developers can have their own environment for personal testing, but `staging` and `production` states should be stored somewhere.

**Comment by Pavel910** [comment]
@mstn I don't push `.serverless` to the repo, although I do know some people who have private repos, and they DO push it.  From personal experience, the SLS CLI itself is not enough to manage the scenario you mentioned. 

The SLS team is working on `remote state storage`, and it should be released very soon, so I'm waiting to see what they come up with.

**Comment by mallize** [comment]
Not supporting ${opt.variable} and ${self.variable} (a core feature of the sls framework) just feels wrong. All of the solutions mentioned above will work, of course, but they are no better than just using AWS Cloud Formation and the CLI (for AWS only). 

I'm confused how supporting ${opt.variable} and ${self.variable} are specific to AWS.

**Comment by martinjuhasz** [comment]
@mallize yeah, i also was confused. what is the reason that serverless components works so differently from serverless itself?

I

**Comment by veloware** [comment]
does this mean that if we need a separate serverless.yml file for each environment, e.g. dev vs prod, if there are any other global variables that could have been passed in as CLI options using v1 serverless, they also now have to be created as a separate serverless file?  Surely this is exponentially going to grow the number of serverless.yml files you have to maintain?

**Comment by veloware** [comment]
Ok, I think that helps, im not precious about using `js` file vs `yml` but I'm curious to see a working solution with a single `yml` file if anyone has one - or if it's not possible and if `js` is the way to go, that's fine.  I think the lack of documentation around such a fundamental change from standard serverless and how you can manage stages / other variables is making this much harder than it should be.

**Comment by hoang-innomizetech** [comment]
Yeah, I know, some tools that we also use doesn't provide a clear way to manage multiple environments deployments and project setup. We started with AWS Amplify hosting component, but it also doesn't provide a way to set up a monorepo that we can deploy multiple apps (each app can have multiple environments). With Serverless Component we can do that

**Comment by francismp** [comment]
I know the conversation here took another path, but any updates on the instance ID thing?

**Comment by eahefnawy** [comment]
@francismp this is a super old issue. It is now completely resolved with Components V2 launching. 

You can now specify a stage simply like this:

```
component: website
name: my-website
stage: prod

inputs:
  src: ./src
```

or via the CLI with `sls deploy --stage prod`

**Comment by theskillwithin** [comment]
@eahefnawy I'm sorry, could you please expand on that a little more for me.

here is where I am at so far

```
name: hv-app
service: hv-app

website:
  component: "@serverless/website"
  inputs:
    code:
      src: dist
      hook: yarn build
    region: us-east-1
    bucketName: hv-app-${opt:stage, 'dev'} ## dev or prod
    # domain: "hv-app"

storybook:
  component: "@serverless/website"
  inputs:
    code:
      src: storybook-static
      hook: yarn build-storybook
    region: us-east-1
    bucketName: hv-app-storybook-${opt:stage, 'dev'} ## dev or prod
    # domain: "hv-app-storybook"
```
