### ISSUE TITLE
sls deploy stopped working after newest version: 2.30.11

### ISSUE THREAD

**Issue by brianzhangassembled** [serverless/components#641]
# Description

seeing error:
"service" property is missing in serverless.yml. 

We have local dev machines that's on older version that can deploy the same project just fine. Is there a work-around for this?

Thanks for your help!

## Additional Data
This only started happening since today: 5/21/2020. Our CI pipeline shows the same build being able to deploy successfully yesterday, starting today the error started showing. We tried rerunning a previous build that passed yesterday, and it fails today. 

E.g. stack trace, version, operating system, ...

serverless.yml file: 
-----------------
component: website
name: company-website
stage: ${opt:stage, 'dev'}
org: orgname

provider:
  name: aws
  region: us-west-1

inputs:
  src:
    src: ./build
-----------------

**Comment by ac360** [comment]
Looking into this right now...

**Comment by ac360** [comment]
Confirmed.  Working on a fix...

**Comment by brianzhangassembled** [comment]
Thank you SOOOOOO much!

**Comment by ac360** [comment]
NP.  We will get this fixed ASAP.  Will respond with an update within 30 minutes.

**Comment by fodurrr** [comment]
same issue here

**Comment by ac360** [comment]
Pushed a fix.  Could you all please uninstall the latest version of Serverless Framework and reinstall it, and try again?

```bash
npm uninstall serverless -g
```

```bash
npm i serverless -g
```

**Comment by ac360** [comment]
@fodurrr @brianzhangassembled @tiffany-ab 

I hope the fix works for you.  We are also implementing a better long-term solution so that this particularly bug cannot happen again.

Thanks for using Components.  We have **big** plans for this product.  Wait until you see what we have coming out over the next few weeks and months. We're just getting started with this effort and it represents over 5 years of serverless application development learnings.
