### ISSUE TITLE
Defining multiple compoents in serverless.yml

### ISSUE THREAD

**Issue by hypexr** [serverless/components#653]
Hello,  In components v1 I defined multiple components in the same serverless.yml like:

```json
getFeed:
  component: "aws-lambda"
  inputs:
    name: ${app}-${component}-${name}-${stage}-getFeed
    handler: getFeed.handler

myApi:
  component: "@serverless/aws-app-sync"
  inputs:
    mappingTemplates:
      - dataSource: GetFeed
        type: Query
        field: getFeed
        request: ${mappingTemplates.genericLambdaRequestPagingInteger}
        response: ${mappingTemplates.genericLambdaResponse}
    dataSources:
      - name: GetFeed
        type: AWS_LAMBDA
        config:
          lambdaFunctionArn: ${getFeed.arn}
```

Each component is defined under a key and components can reference each other's output variables as is done in myApi `${getFeed.arn}`.

How do I do something similar with components v2?  All of the examples define `component` at the top level.  I'm not sure how I would deploy multiple lambdas using the `aws-lambda` component.

Thanks!

**Comment by hypexr** [comment]
After reading the readme I understand how this works now.  Closing.

**Comment by m4tta** [comment]
That makes one of us. Because I still can't figure out how to work with multiple components. Surely they don't expect us to liter our project with serverless.yml files everywhere?

If i need to create 3 dynamodb tables do i need to make 3 separate serverless.yml files and since they need that name i need to put each one it its own folder?
