### ISSUE TITLE
Lambda@Edge for components (express)

### ISSUE THREAD

**Issue by shivam-raj** [serverless/components#725]
I've been using Serverless Framework to build a full stack application
My backend is in Express. I wanted to deploy this lambda function for express to lambda@edge.
Is there like a simpler way to do it?

**Comment by eahefnawy** [comment]
Unfortunately, components do not support Lambda@Edge atm. We might have a component for that soon though.

Lambda@Edge was not meant for express applications though, and I don't think it would even work because express lambdas need API Gateway, while Lambda@Edge hooks up with CloudFront. How would routing work in that case?! 🤔

**Comment by shivam-raj** [comment]
You're right...Sorry dumb question it was
Excited for Lambda@Edge component :+1:
